---

- cron:
    name: "dump db"
    minute: "{{ cron_minutes }}"
    hour: "{{ cron_hours }}"
    user: "{{ postgres_user }}"
    job: /usr/bin/pg_dump -Fc {{ db_name }} > {{db_backup_folder}}/{{ db_name }}_`/bin/date "+\%Y-\%m-\%dT\%H-\%M-\%S"`.dump
  tags: backups
