---

- name: Setup basic security settings for a Cattail web server
  hosts: all
  remote_user: root
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml

  roles:
    - security
